# Deep Learning for Article Classification with Publication using Kaggle Data

Here is the link for data - https://www.kaggle.com/snapcrack/all-the-news (courtesy of Andrew Thompson)

------------

**We will build a text classifier with Keras and 1-D Convolutional Neural Networks for the Kaggle dataset containing information such as title, author, publication and the content of the article. This data set includes several publications but we focus on top 5 publications (all US publishers) as labels acting for the title and content as features. Below is the description of labels.**

    Label	Description
    0	    Breitbart
    1	    New York Post
    2	    NPR (National Public Radio)
    3	    Washington Post
    4	    Reuters

## The Data

**The code below is meant to connect to drive for accessing the dataset**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### Importing some libraries

In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

## For Cleaning and Decoding
import re
import html
import unicodedata
import string
import glob

from tqdm import tqdm

In [3]:
## For Preparing Features to Model
import nltk

from nltk.tokenize import RegexpTokenizer
from nltk.stem.snowball import SnowballStemmer

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer


## For Bonus Section
try:
    from gensim.models import word2vec
except:
    !pip install gensim
    from gensim.models import word2vec

## For Data Exploration
try:
    from wordcloud import WordCloud
except:
    !pip install wordcloud
    from wordcloud import WordCloud

In [4]:
from textblob import Word
from string import punctuation
from gensim.parsing.preprocessing import STOPWORDS

In [5]:
nltk.download("stopwords")
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


**Use your own gdrive directory to access the files you store on your gdrive**

**Or just directly have it ready in your working directory**

In [15]:
articles_loc = glob.glob("./drive/MyDrive/UofT/Deep NN Projects/Keras-ArticlePublishersData-1D-CNN-MC/articles/*.csv")

In [16]:
articles_loc

['./drive/MyDrive/UofT/Deep NN Projects/Keras-ArticlePublishersData-1D-CNN-MC/articles/articles2.csv',
 './drive/MyDrive/UofT/Deep NN Projects/Keras-ArticlePublishersData-1D-CNN-MC/articles/articles1.csv',
 './drive/MyDrive/UofT/Deep NN Projects/Keras-ArticlePublishersData-1D-CNN-MC/articles/articles3.csv']

In [17]:
df1 = pd.read_csv(articles_loc[0])
df1.head()

Unnamed: 0     id  ...  url                                            content
0       53293  73471  ...  NaN  Patriots Day, Peter Berg’s new thriller that r...
1       53294  73472  ...  NaN  In Norse mythology, humans and our world were ...
2       53295  73474  ...  NaN  “If our democracy is to work in this increasin...
3       53296  73475  ...  NaN  Updated on January 11 at 5:05 p. m. In his fir...
4       53297  73476  ...  NaN  Updated at 12:25 p. m. After months of equivoc...

[5 rows x 10 columns]

In [18]:
df2 = pd.read_csv(articles_loc[1])
df2.head()

Unnamed: 0     id  ... url                                            content
0           0  17283  ... NaN  WASHINGTON  —   Congressional Republicans have...
1           1  17284  ... NaN  After the bullet shells get counted, the blood...
2           2  17285  ... NaN  When Walt Disney’s “Bambi” opened in 1942, cri...
3           3  17286  ... NaN  Death may be the great equalizer, but it isn’t...
4           4  17287  ... NaN  SEOUL, South Korea  —   North Korea’s leader, ...

[5 rows x 10 columns]

In [19]:
df3 = pd.read_csv(articles_loc[2])
df3.head()

Unnamed: 0  ...                                            content
0      103459  ...  The son of a Louisiana man whose father was sh...
1      103460  ...  Copies of William Shakespeare’s first four boo...
2      103461  ...  Debt: $20, 000, Source: College, credit cards,...
3      103462  ...  It was late. I was drunk, nearing my 35th birt...
4      103463  ...  A central Texas man serving a life sentence fo...

[5 rows x 10 columns]

In [20]:
df1.columns==df2.columns, df2.columns==df3.columns #Checking all columns are same

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]))

In [21]:
# Merging to a single dataset
df = pd.concat([df1, df2, df3], axis=0)
df.reset_index(inplace=True, drop=True)

In [22]:
# Dropping columns not required
df.drop(['Unnamed: 0', 'date', 'year', 'month', 'url'], axis=1, inplace=True)

## Data Cleaning

In [23]:
# Checking for null values
df.isnull().sum()

id                 0
title              2
publication        0
author         15876
content            0
dtype: int64

In [24]:
# Dropping null values
df.dropna(inplace=True)

In [25]:
df.isnull().sum()

id             0
title          0
publication    0
author         0
content        0
dtype: int64

In [26]:
df.head()

id  ...                                            content
0  73471  ...  Patriots Day, Peter Berg’s new thriller that r...
1  73472  ...  In Norse mythology, humans and our world were ...
2  73474  ...  “If our democracy is to work in this increasin...
3  73475  ...  Updated on January 11 at 5:05 p. m. In his fir...
4  73476  ...  Updated at 12:25 p. m. After months of equivoc...

[5 rows x 5 columns]

In [27]:
df.tail()

id  ...                                            content
142565  218078  ...           Uber driver Keith Avila picked up a p...
142566  218079  ...           Crews on Friday continued to search L...
142567  218080  ...       When the Obama administration announced a...
142568  218081  ...       This story has been updated. A new law in...
142569  218082  ...       The nation’s first recreational marijuana...

[5 rows x 5 columns]

In [28]:
# Getting count of articles for each publication
df['publication'].value_counts()

Breitbart              23781
New York Post          17485
NPR                    11654
Washington Post        11077
Reuters                10709
New York Times          7767
Guardian                7250
CNN                     7025
National Review         6203
Atlantic                6199
Business Insider        4950
Vox                     4947
Buzzfeed News           4853
Talking Points Memo     1676
Fox News                1117
Name: publication, dtype: int64

In [29]:
# Identifying length of title
df['len_title'] = [len(x) for x in df['title']]

In [30]:
# Identifying length of content
df['len_content'] = [len(x) for x in df['content']]

In [31]:
df.head()

id  ... len_content
0  73471  ...        5357
1  73472  ...        8015
2  73474  ...        5096
3  73475  ...        5773
4  73476  ...        2445

[5 rows x 7 columns]

### Filtering for Top-5 Publications

In [32]:
top_publications = df.publication.value_counts()[:5] 
sum(top_publications.values)

74706

In [33]:
top_publications # Printing the count and names of publications

Breitbart          23781
New York Post      17485
NPR                11654
Washington Post    11077
Reuters            10709
Name: publication, dtype: int64

In [34]:
# Drop rows that are not in the top_writer
df_top = pd.DataFrame(columns=df.columns)
for i in top_publications.keys():
    df_top = df_top.append(df[df.publication == i], ignore_index=True)
df = df_top
del df_top

In [35]:
df

id  ... len_content
0       26539  ...        1067
1       26540  ...        1514
2       26541  ...        2195
3       26542  ...        2113
4       26543  ...        3866
...       ...  ...         ...
74701  195402  ...        4670
74702  195403  ...        6011
74703  195404  ...        3243
74704  195410  ...        6482
74705  195417  ...        4830

[74706 rows x 7 columns]

### Filtering for datapoints that have considerable text to process with

In [36]:
df = df[df['len_content']>150]

In [37]:
df = df[df['len_title']>5]

In [38]:
df.describe() # Not a considerable decrease in amount

id                           title  ... len_title len_content
count    74548                           74548  ...     74548       74548
unique   74548                           74540  ...       160       10913
top     131071  The best upcoming sample sales  ...        63        2878
freq         1                               3  ...      2341          36

[4 rows x 7 columns]

In [39]:
df['publication'].value_counts() # Final count of articles for publications

Breitbart          23664
New York Post      17481
NPR                11646
Washington Post    11048
Reuters            10709
Name: publication, dtype: int64

## Data Processing

In [40]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [41]:
def process_row(row):
    
    #Mail address
    row = re.sub('(\S+@\S+)(com|\s+com)', ' ', row)
    #Username
    row = re.sub('(\S+@\S+)', ' ', row)
    #punctuation
    # punctuation = punctuation + '\n' + '—“,”‘-’' + '0123456789'
    punctuation = '—“,”‘-’' + '0123456789'
    row = ''.join(word for word in row if word not in punctuation)
    #Lower case 
    row = row.lower()
    #Stopwords
    stop = STOPWORDS
    row = ' '.join(word for word in row.split() if word not in stop)    
    #Lemma
    row = " ".join([Word(word).lemmatize() for word in row.split()])
    #Stemming
    stemmer = SnowballStemmer(language='english')
    row = " ".join([stemmer.stem(word) for word in row.split()])
    #Extra whitespace
    row = re.sub('\s{1,}', ' ', row)
    
    row = " ".join([word for word in row.split() if len(word) > 2])

    return row

In [42]:
df.shape

(74548, 7)

In [43]:
df['content_clean'] = df['content'].apply(process_row) # Processing on Content

In [45]:
df

id  ...                                      content_clean
0       26539  ...  tuesday broadcast cnns situat room cnn senior ...
1       26540  ...  group american spring break revel report chant...
2       26541  ...  honour crime risen cent year london number for...
3       26542  ...  breitbart senior editor milo announc found new...
4       26543  ...  focus continu medium report alleg collus russi...
...       ...  ...                                                ...
74701  195402  ...  net long bet dollar fell week time octob rebou...
74702  195403  ...  wall street ralli derail renew worri donald tr...
74703  195404  ...  (reuter breakingviews) walt disney look bit ma...
74704  195410  ...  (stori refil correct date paragraph lisa richw...
74705  195417  ...  european capit tighten secur friday ahead new ...

[74548 rows x 8 columns]

    0	    Breitbart
    1	    New York Post
    2	    NPR (National Public Radio)
    3	    Washington Post
    4	    Reuters

**Dumping the dataset onto gdrive. Change directory if you want to**

In [51]:
df.to_pickle("./drive/MyDrive/UofT/Deep NN Projects/Keras-ArticlePublishersData-1D-CNN-MC/dataset.pkl")

## Preparing Data for Modeling


In [52]:
from sklearn import preprocessing
from tensorflow.keras.utils import to_categorical

**Encoding the label - publications**

In [53]:
le = preprocessing.LabelEncoder()

In [54]:
df['publication_label'] = le.fit_transform(df.publication.values)

**Setting Targets & Features**

In [56]:
X = df['content_clean'].values

In [57]:
y = df['publication_label'].values

In [58]:
y

array([0, 0, 0, ..., 3, 3, 3])

**Converting label as one-hot encoded matrix**

In [59]:
to_categorical(y)

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)

**Splitting for training and testing sets**

In [60]:
from sklearn.model_selection import train_test_split

In [61]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=42, stratify=y)

In [62]:
y_train_cat = to_categorical(y_train)
y_test_cat = to_categorical(y_test)

**Storing the prepared data for modeling**

In [63]:
pd.DataFrame(X_train).to_pickle("./drive/MyDrive/UofT/Deep NN Projects/Keras-ArticlePublishersData-1D-CNN-MC/X_train.pkl")
pd.DataFrame(X_test).to_pickle("./drive/MyDrive/UofT/Deep NN Projects/Keras-ArticlePublishersData-1D-CNN-MC/X_test.pkl")

In [64]:
pd.DataFrame(y_train_cat).to_pickle("./drive/MyDrive/UofT/Deep NN Projects/Keras-ArticlePublishersData-1D-CNN-MC/y_train_cat.pkl")
pd.DataFrame(y_test_cat).to_pickle("./drive/MyDrive/UofT/Deep NN Projects/Keras-ArticlePublishersData-1D-CNN-MC/y_test_cat.pkl")

### This is the end of Part-1. In the second part, we will pick up here with some feature encoding and finally model building, fitting & evaluation